AY2425S1-CS2103T-W14-2/tp

src/main/java/seedu/address/logic/commands/ExportCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/ExportCommandParser.java
src/test/java/seedu/address/logic/commands/ExportCommandTest.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java

The function hasn't been fully implemented yet but it has been hooked into the application + designed to accept parameters.

Add partial CSV export functionality

---

src/main/java/seedu/address/logic/commands/ExportCommand.java
src/test/java/seedu/address/logic/commands/ExportCommandTest.java

Added tests for the export helper functions under `ExportCommand.java`. This should help with more extensive code coverage.

Add tests for export helper functions

---

.gitignore
src/main/java/seedu/address/logic/commands/SortCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/logic/parser/SortCommandParser.java
src/main/java/seedu/address/model/tag/Tag.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/JsonAdaptedTag.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/SortCommandTest.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
src/test/java/seedu/address/model/tag/TagTest.java
src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
src/test/java/seedu/address/testutil/TypicalPersons.java

Adds the logic for Sort command into BA€.
Also implements (optional) values for Tag class.
Changes to JSON parsing for Tag class to accommodate optional Tag values.

Add Sort command functionality

---

docs/diagrams/ExportCommand.puml

Create export diagram

---

docs/UserGuide.md

- Quick Start Section
- Command Summary

Update UG Miscellaneous

---

src/main/java/seedu/address/logic/commands/SortCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/SortCommandParser.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java

Implements first iteration of SortCommand. Allows user to show contacts that contain the specified tag in ascending or descending order.
Closes #73 
Still yet to include unit tests for SortCommand.

Implement Sort Command feature

---

src/main/java/seedu/address/model/person/Name.java
src/main/java/seedu/address/model/person/Phone.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/model/person/PersonTest.java
src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java

- Initially we can add 2 people with the same name but different case
- Which is not expected behavior
- So changed comparator for Name class

Duplicate detection limitation

---

build.gradle
src/main/java/seedu/address/logic/commands/ClearCommand.java
src/main/java/seedu/address/logic/commands/FilterCommand.java
src/main/java/seedu/address/ui/AlertFactory.java
src/test/java/seedu/address/logic/commands/ClearCommandTest.java
src/test/java/seedu/address/logic/commands/FilterCommandTest.java

- Implemented a popup window for confirmation when user wants to clear
- Added testing
- Modified FilterCommand predicate logic
- Added FilterCommand testing for partial tags match

Implement Clear Command Popup Window

---

src/main/java/seedu/address/logic/commands/AdvFilterCommand.java
src/main/java/seedu/address/logic/parser/AdvFilterCommandParser.java
src/test/java/seedu/address/logic/commands/AdvFilterCommandTest.java
src/test/java/seedu/address/logic/parser/AdvFilterCommandParserTest.java

Now checks if user input contains valid operator and shows Invalid Command text etc otherwise. Resolves #131.
Fixed comparison using operators and between Double and String types. In particular:
resolves #135 and resolves #136

AdvFilterCommandParser.java: Check for valid operators when parsing

---

src/main/java/seedu/address/model/person/Name.java
src/test/java/seedu/address/model/person/NameTest.java

Names now also no longer accept backslashes
Relevant test cases added in NameTest.java

Names should accept apostrophes

---

src/main/java/seedu/address/logic/parser/ParserUtil.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java

for  Able to edit tags to have the same key but different values #138

Fix tag key duplicates

---

docs/DeveloperGuide.md
docs/UserGuide.md

i have not yet tested these commands, don't approve it until the commands have been tested. Also not sure about testing the save data function

Add manual testing instructions

---

src/main/java/seedu/address/logic/parser/SortCommandParser.java
src/test/java/seedu/address/logic/commands/SortCommandTest.java
src/test/java/seedu/address/logic/parser/SortCommandParserTest.java

- Added additional checking in SortCommand for valid tag
- Added testing for SortCommand and SortCommandParser

Add Testing for SortCommand

---

src/main/java/seedu/address/ui/MainWindow.java
src/main/resources/view/MainWindow.fxml

- Resolves #200 and #202.
- Fixes export button issues by reinstating the functionality of the "Export to CSV" GUI button.
- Added a new "Export to TXT" GUI button.

Add CSV and TXT export GUI buttons

---

src/main/java/seedu/address/model/tag/Tag.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java

- I am sorry
- I made the wrong merged wrongly

Incorrect merge conflict resolution

---

docs/UserGuide.md

- Resolves #173.
- Unrelated to the issues shown in #218. However, the changes in this PR make minor improvements to the current state of the user guide.

Update UG: Add/Refine minor details.

---

docs/UserGuide.md

Update User Guide for Sort Command

---

docs/DeveloperGuide.md
src/main/java/seedu/address/logic/commands/ExportCommand.java

Resolves #239 and #267. 
Most of the issues mentioned in this issue are regressions that were correct in earlier versions.
Changelog:
- Fixed errors in-app usage guide for `export`.
- Updated `export`'s test case in the DG manual testing guide.

Update `export`'s documentation across the product

---

docs/DeveloperGuide.md
docs/diagrams/FilterSequenceDiagram.puml
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/tag/Tag.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java

This fixes the following bugs: #271 , #269 , #258 
#271 
- I added another method called isValidTagValue
- Separated value and key regex. for  key accepts all alphanumeric and decimals
#269 
-made sure fi and social media handles only take in one input
#258 
- Changed the UML for backslashes
- and some other minor UI fix

Fix PE-D issues

---

src/main/java/seedu/address/logic/commands/SortCommand.java
src/test/java/seedu/address/logic/commands/SortCommandTest.java

Fix sort behvaiour to be case-insensitive

---

docs/UserGuide.md

Update UG for clarity and consistency

---

src/main/java/seedu/address/logic/commands/ExportCommand.java
src/test/java/seedu/address/logic/commands/ExportCommandTest.java

Reformat tags in TXT exports
